In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
# loading the dataset to a pandas dataframe
credit_card_data = pd.read_csv("/content/sample_data/creditcard.csv")

In [3]:
credit_card_data.head()

   Time        V1        V2        V3  ...       V27       V28  Amount  Class
0   0.0 -1.359807 -0.072781  2.536347  ...  0.133558 -0.021053  149.62      0
1   0.0  1.191857  0.266151  0.166480  ... -0.008983  0.014724    2.69      0
2   1.0 -1.358354 -1.340163  1.773209  ... -0.055353 -0.059752  378.66      0
3   1.0 -0.966272 -0.185226  1.792993  ...  0.062723  0.061458  123.50      0
4   2.0 -1.158233  0.877737  1.548718  ...  0.219422  0.215153   69.99      0

[5 rows x 31 columns]

In [4]:
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [5]:
credit_card_data['Class'].value_counts()
# this implies that data is very unbalanced

Class
0    284315
1       492
Name: count, dtype: int64

data is highly unbalanced

0 --> normal transaction
1 --> fraud transaction

In [6]:
# seperating the data for analysis
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [7]:
# statistical measures of the data
legit.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [8]:
fraud.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [9]:
# compare the values for both transaction
credit_card_data.groupby('Class').mean()

               Time        V1        V2  ...       V27       V28      Amount
Class                                    ...
0      94838.202258  0.008258 -0.006271  ... -0.000295 -0.000131   88.291022
1      80746.806911 -4.771948  3.623778  ...  0.170575  0.075667  122.211321

[2 rows x 30 columns]

**Under-sampling**

Build a sample data set containing similar distribution of legit transaction and the fraudulant transaction

number of fraud transaction --> 492

In [10]:
# randomly select 492 data from legit sample
legit_sample = legit.sample(n=492)

Concatenate two dataframes

In [11]:
new_dataset = pd.concat([legit_sample, fraud],axis=0)

In [12]:
new_dataset.head()

            Time        V1        V2  ...       V28  Amount  Class
176131  122639.0 -0.965636 -0.579696  ...  0.132841   44.90      0
226862  144832.0  1.992159  0.108483  ... -0.052033   51.74      0
127384   78312.0  1.201741  0.117589  ...  0.008370    1.98      0
246830  153344.0 -0.982130  1.689701  ...  0.110639    1.79      0
282498  170939.0 -1.113998 -0.592489  ...  0.095562   86.64      0

[5 rows x 31 columns]

In [13]:
new_dataset.tail()

            Time        V1        V2  ...       V28  Amount  Class
279863  169142.0 -1.927883  1.125653  ...  0.147968  390.00      1
280143  169347.0  1.378559  1.289381  ...  0.186637    0.76      1
280149  169351.0 -0.676143  1.126366  ...  0.194361   77.89      1
281144  169966.0 -3.113832  0.585864  ... -0.253700  245.00      1
281674  170348.0  1.991976  0.158476  ... -0.015309   42.53      1

[5 rows x 31 columns]

In [15]:
new_dataset['Class'].value_counts()

Class
0    492
1    492
Name: count, dtype: int64

In [16]:
new_dataset.groupby('Class').mean()

               Time        V1        V2  ...       V27       V28      Amount
Class                                    ...
0      94331.193089 -0.088168  0.012924  ...  0.007882 -0.013501  104.252256
1      80746.806911 -4.771948  3.623778  ...  0.170575  0.075667  122.211321

[2 rows x 30 columns]

split dataset into feature and target

In [17]:
x = new_dataset.drop(columns='Class',axis=1)
y = new_dataset['Class']

In [18]:
print(x)
print(y)

            Time        V1        V2  ...       V27       V28  Amount
176131  122639.0 -0.965636 -0.579696  ... -0.129423  0.132841   44.90
226862  144832.0  1.992159  0.108483  ... -0.056396 -0.052033   51.74
127384   78312.0  1.201741  0.117589  ... -0.040485  0.008370    1.98
246830  153344.0 -0.982130  1.689701  ... -0.063238  0.110639    1.79
282498  170939.0 -1.113998 -0.592489  ... -0.069412  0.095562   86.64
...          ...       ...       ...  ...       ...       ...     ...
279863  169142.0 -1.927883  1.125653  ...  0.292680  0.147968  390.00
280143  169347.0  1.378559  1.289381  ...  0.389152  0.186637    0.76
280149  169351.0 -0.676143  1.126366  ...  0.385107  0.194361   77.89
281144  169966.0 -3.113832  0.585864  ...  0.884876 -0.253700  245.00
281674  170348.0  1.991976  0.158476  ...  0.002988 -0.015309   42.53

[984 rows x 30 columns]
176131    0
226862    0
127384    0
246830    0
282498    0
         ..
279863    1
280143    1
280149    1
281144    1
281674    1
Name: Class, Length: 984, dtype: int64

Split into train and test data

In [19]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,stratify=y,random_state=2)

Model Training

Logistic Regression Model

In [20]:
model = LogisticRegression()

In [21]:
# traing the model with training data
model.fit(x_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

Model Evaluation

Accuracy score

In [22]:
# accuracy on training data
x_train_prediction = model.predict(x_train)
training_data_accuracy = accuracy_score(x_train_prediction,y_train)
print("training_data_accuracy: ",training_data_accuracy)

training_data_accuracy:  0.9466327827191868

In [23]:
# accuracy on test data
x_test_prediction = model.predict(x_test)
test_data_accuracy = accuracy_score(x_test_prediction,y_test)
print("test_data_accuracy: ",test_data_accuracy)

test_data_accuracy:  0.934010152284264

In [29]:
data = (0,-1.3598071336738,-0.0727811733098497,2.53634673796914,1.37815522427443,-0.338320769942518,0.462387777762292,0.239598554061257,0.0986979012610507,0.363786969611213,0.0907941719789316,-0.551599533260813,-0.617800855762348,-0.991389847235408,-0.311169353699879,1.46817697209427,-0.470400525259478,0.207971241929242,0.0257905801985591,0.403992960255733,0.251412098239705,-0.018306777944153,0.277837575558899,-0.110473910188767,0.0669280749146731,0.128539358273528,-0.189114843888824,0.133558376740387,-0.0210530534538215,149.62)
data_as_np_array = np.asarray(data)
data_reshaped = data_as_np_array.reshape(1,-1)
prediction = model.predict(data_reshaped)
print(prediction)

if (prediction==0):
  print("The transaction is legit")
else:
  print("The transaction is fraud")

[0]
The transaction is legit

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(